name: ProductsManagement

on:
  push:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure Log In 
        uses: azure/login@v1          
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
    
      - name: Restore dependencies
        run: dotnet restore ./ShopMicroservices.ProductsManagement.Api/ShopMicroservices.ProductsManagement.Api.csproj

      - name: Build
        run: dotnet build ./ShopMicroservices.ProductsManagement.Api/ShopMicroservices.ProductsManagement.Api.csproj --configuration Release --no-restore
