name: ProductsManagement

on:
  push:
    branches:
      - master

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Log In to Azure
        uses: azure/login@v1          
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Azure Log In to Azure Container Registry 
        uses: azure/docker-login@v1          
        with:
          login-server: ${{secrets.ARC_LOGIN_SERVER}}
          username: ${{secrets.ARC_USERNAME}}
          password: ${{secrets.ARC_PASSWORD}}

      - name: Get current date in yyyyMMdd format
        run: echo "DATE_TIME = $(date + '%Y%m%d')" >> $GITHUB_ENV   

      - name: Build and push container image
        run: 
            docker build -f src/ShopMicroservices.ProductsManagement.Api/Dockerfile -t ${{secrets.ARC_LOGIN_SERVER}}/products-management-api:${{env.DATE_TIME}}.${{github.run_number}}
            docker push ${{secrets.ARC_LOGIN_SERVER}}/products-management-api:${{env.DATE_TIME}}.${{github.run_number}}
    